$primary = rgb(f2cbb4)
$surface = rgb(291c14)
$secondary = rgb(eee7b8)
$error = rgb(fd4663)
$tertiary = rgb(daeeb8)
$surface_lowest = rgb(150e0a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
