$primary = rgb(e56b71)
$surface = rgb(291415)
$secondary = rgb(dca374)
$error = rgb(c07466)
$tertiary = rgb(d3cf7d)
$surface_lowest = rgb(150a0a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
