$primary = rgb(e59069)
$surface = rgb(291b14)
$secondary = rgb(dcc872)
$error = rgb(cf987f)
$tertiary = rgb(b8d37b)
$surface_lowest = rgb(150d0a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
