cursor #e1e2e8
cursor_text_color #c1c7d1

foreground            #e1e2e8
background            #111417
selection_foreground  #1d3248
selection_background  #b3c8e4
url_color             #9ccaff

color0   #111417
color1   #ff729c
color2   #7fff90
color3   #fff772
color4   #81b5f2
color5   #214976
color6   #9ccaff
color7   #eff6ff
color8   #999fa5
color9   #ff9fbb
color10  #a5ffb1
color11  #fffaa5
color12  #aad1ff
color13  #b9d9ff
color14  #d2e7ff
color15  #f8fbff
