cursor #e7e1df
cursor_text_color #d1c4bc

foreground            #e7e1df
background            #151312
selection_foreground  #362f2a
selection_background  #d0c4bd
url_color             #d6c3b4

color0   #151312
color1   #f6756e
color2   #7dd66b
color3   #ffe672
color4   #cbb5a4
color5   #635246
color6   #d6c3b4
color7   #e0d8d3
color8   #8b8480
color9   #ffa49f
color10  #b5ffa5
color11  #ffefa5
color12  #ebd9cb
color13  #ffefe2
color14  #fff4ec
color15  #fffbf8
