cursor #e0e3e7
cursor_text_color #bfc7d0

foreground            #e0e3e7
background            #101417
selection_foreground  #153345
selection_background  #adcae1
url_color             #86ceff

color0   #101417
color1   #ff729e
color2   #7fff8f
color3   #fff672
color4   #68baf2
color5   #0f4c76
color6   #86ceff
color7   #eff8ff
color8   #99a0a5
color9   #ff9fbd
color10  #a5ffb0
color11  #fff9a5
color12  #98d5ff
color13  #aadcff
color14  #c8e8ff
color15  #f8fcff
